name: "TEST"
on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Run curl
         run: |
           env
           echo "::add-mask::$ACTIONS_ID_TOKEN_REQUEST_TOKEN"

