name: "TEST"
on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Run curl
         run: |
           curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"
